### ISSUE TITLE
Server side rendering error: window is not defined

### ISSUE THREAD

**Issue by adammcodes** [Teamwork/public-components#7]
Hi! I am using the login-button component in Next.js v 13, and despite all attempts to indicate `"use client"` or check if `typeof window !== "undefined"` and also the `useEffect()` method for ensuring client code only runs on the client, I keep getting the same server ReferenceError from this package: 

```
⨯ node_modules/@teamwork/login-button/dist/login-button.js (13:9232) @ eval
 ⨯ ReferenceError: window is not defined
    at __webpack_require__ (/Users/adammarsala/mavenmm/tw-auth-starter/tw-auth-template/.next/server/webpack-runtime.js:33:42)
    at eval (./components/LoginButton.js:7:80)
    at (ssr)/./components/LoginButton.js (/Users/adammarsala/mavenmm/tw-auth-starter/tw-auth-template/.next/server/app/page.js:173:1)
    at __webpack_require__ (/Users/adammarsala/mavenmm/tw-auth-starter/tw-auth-template/.next/server/webpack-runtime.js:33:42)
    at eval (./app/page.tsx:14:81)
    at (ssr)/./app/page.tsx (/Users/adammarsala/mavenmm/tw-auth-starter/tw-auth-template/.next/server/app/page.js:162:1)
    at __webpack_require__ (/Users/adammarsala/mavenmm/tw-auth-starter/tw-auth-template/.next/server/webpack-runtime.js:33:42)
```

I think the only references to `window` in the module are made at the very bottom of `login-button.js` and they are only used for testing. 

Is it possible to remove these references or edit them so they don't cause a back-end error in the Next framework?

I am open to any other Next specific solutions, but none have worked for me so far.

**Comment by ripexz** [comment]
Hey @MagicMark5 - we've just released 1.0.1 that should hopefully address the issue (added a check if window is defined - should avoid the reference error).

Feel free to reopen if the issue persists. 😊
